PhuKienDienThoai/Areas/Users/Controllers/MatKhauController.cs
using System;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhuKienDienThoai.Controllers;
using PhuKienDienThoai.Models;
using PhuKienDienThoai.Models.ManageViewModels;
using PhuKienDienThoai.Services;

namespace PhuKienDienThoai.Areas.Users.Controllers
{
    [Area("Users")]
    [Authorize(Roles = "Admin, User")]
    public class MatKhauController : Controller
    {
         UserManager<ApplicationUser> usermanager;
         SignInManager<ApplicationUser> _signInManager;
         IEmailSender _emailSender;
         ILogger<ManageController> _logger;
         UrlEncoder _urlEncoder;
        IHostingEnvironment  _enviroment;

        public MatKhauController(
            UserManager<ApplicationUser> _usermanager,
            SignInManager<ApplicationUser> signInManager,
            IHostingEnvironment  environment,
            IEmailSender emailSender,
            ILogger<ManageController> logger,
            UrlEncoder urlEncoder)
        {
            usermanager = _usermanager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = logger;
            _urlEncoder = urlEncoder;
            _enviroment = environment;
        }
        protected override void Dispose(bool disposing)
        {
            if(disposing)
                usermanager.Dispose();
        }
        public IActionResult Index() => View();
        public IActionResult DoiMatKhau()
        {
            var changePassword = new ChangePasswordViewModel();
            return View(changePassword);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DoiMatKhau(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var user = await usermanager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{usermanager.GetUserId(User)}'.");
            var kiemtraMatKhauCu = await usermanager.CheckPasswordAsync(user, model.OldPassword);
            if (!kiemtraMatKhauCu)
                TempData["Message"] = "Mật khẩu cũ không khớp, vui lòng nhập lại";
            var changePasswordResult = await usermanager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                Logs.Logger.Log(changePasswordResult.ToString());
                return View(model);
            }

            await _signInManager.SignInAsync(user, isPersistent: false);
            _logger.LogInformation(message: "User changed their password successfully.");
            TempData["Message"] = "Thay đổi mật khẩu thành công.";
            return RedirectToAction(nameof(DoiMatKhau));
        }
    }
}

PhuKienDienThoai/Areas/Users/Views/MatKhau/DoiMatKhau.cshtml
@{
    Layout="_MainLayout";
    ViewData["HeadTitle"]="Thay đổi mật khẩu";
}
@using PhuKienDienThoai.Models.ManageViewModels
@model ChangePasswordViewModel
<h3 class="heading">Thay đổi mật khẩu</h3>
@if(@TempData["Message"]!=null)
{
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Thông báo</strong> @TempData["Message"]
    </div>
}
<div class="row">
    <div class="col-md-6">
        <form method="post" asp-area="Users" asp-action="DoiMatKhau" asp-controller="MatKhau">
            <div asp-validation-summary="All" class="text-danger"></div>
        
            <div class="form-group">
                <label asp-for="OldPassword"></label>
                <input type="password" class="form-control" asp-for="OldPassword">
                <span asp-validation-for="OldPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewPassword"></label>
                <input type="password" class="form-control" asp-for="NewPassword">
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input type="password" class="form-control" asp-for="ConfirmPassword">
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button class="btn add-to-cart pull-right">Thay đổi mật khẩu</button>
        </form>  
    </div>
</div>